# Hetro associative Memory

## Kshitiz Gehlot
## 2017UIT2614

In [1]:
import numpy as np

## Activation function

In [2]:
@np.vectorize
def AF(x):
    return np.where(x>0, 1, -1)

## Function to train on given inputs

In [3]:
def train(X, W, T):
    W += X.T@T
    return W

## Function to predict

In [4]:
def pred(X, W):
    return AF(X@W)

## Main code

In [5]:
# Initialization
X = np.array([[-1, 1, 1, 1], [1, 1, 1, -1], [-1, -1, 1, 1], [1, 1, -1, -1]]).reshape(4, 4)
Y = np.array([[-1, 1], [1, -1], [-1, 1], [1, -1]]).reshape(4, 2)

Inputs

In [6]:
X

array([[-1,  1,  1,  1],
       [ 1,  1,  1, -1],
       [-1, -1,  1,  1],
       [ 1,  1, -1, -1]])

Outputs

In [7]:
Y

array([[-1,  1],
       [ 1, -1],
       [-1,  1],
       [ 1, -1]])

In [8]:
W = np.zeros((4, 2))

### Training

In [9]:
# Training
W = train(X, W, Y)

Final Weights

In [10]:
W

array([[ 4., -4.],
       [ 2., -2.],
       [-2.,  2.],
       [-4.,  4.]])

### Testing

In [11]:
#Predicting
print(f"Output with original inputs- {pred(X, W)}")

Output with original inputs- [[-1  1]
 [ 1 -1]
 [-1  1]
 [ 1 -1]]


In [12]:
# Taking missing and mistaken entry
X1 = np.array(X)
X1[0, 1] = 0
X2 = np.array(X)
X2[0, 2] *= -1

In [14]:
print(f"Output with 1 missing entry on {X1[0]}- {pred(X1[0], W)}")
print(f"Output with 1 mistaken entry on {X2[0]}- {pred(X2[0], W)}")

Output with 1 missing entry on [-1  0  1  1]- [-1  1]
Output with 1 mistaken entry on [-1  1 -1  1]- [-1  1]
